services:
  api:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .env

volumes:
  postgres_data:
