# Generated by Django 5.0.6 on 2024-05-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_order_items_remove_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='in_stock',
            new_name='stock',
        ),
    ]
