# Generated by Django 5.0.6 on 2024-05-26 04:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_review_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ProductReview',
        ),
    ]
