# Generated by Django 5.0.6 on 2024-05-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set(),
        ),
    ]
